name: CI Quality Checks
on: 
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    quality-checks:
        runs-on: ubuntu-latest
        env:
              FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.14'

            - name: Install Poetry
              run: pipx install poetry

            - name: Install dependencies
              run: poetry install

            - name: Run Quality Suite
              run: make check